if(F)
{
  file.edit("Rawal_et_al_HCB_2024/subscripts/GO_enrichment.R")
  file.edit("Rawal_et_al_HCB_2024/subscripts/GO_boxplot_FC.R")
  file.edit("Rawal_et_al_HCB_2024/subscripts/GO_barplot_N_genes.R")
  file.edit("Rawal_et_al_HCB_2024/subscripts/Hilbert_curves_H3K27me3_H2AK118Ub.R")
  file.edit("Rawal_et_al_HCB_2024/subscripts/enrichment_ratios_H3K27me3_H2AK118Ub.R")
  file.edit("Rawal_et_al_HCB_2024/subscripts/genes_table_GO_terms.R")
}